### ISSUE TITLE
Implement recommendations from the Electron security checklist

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#1437]
**Is your feature request related to a problem? Please describe.**
[This checklist](https://www.electronjs.org/docs/tutorial/security) lists best practices regarding security in Electron apps. Currently we're not following all of it. The risk was evaluated as relatively low, however since then a lot of time has passed, things could've changed.

**Describe the solution you'd like**
We should re-evaluate existing violations and fix what's possible.

List of improvements:

- [x] [Only Load Secure Content](https://www.electronjs.org/docs/tutorial/security#1-only-load-secure-content): we don't load anything over http, but we should also explicitly enforce it
- [x] [Do Not Disable WebSecurity](https://www.electronjs.org/docs/tutorial/security#5-do-not-disable-websecurity): for popups
- [x] [Define a Content Security Policy](https://www.electronjs.org/docs/tutorial/security#6-define-a-content-security-policy)
- [x] [Do Not Set allowRunningInsecureContent to true](https://www.electronjs.org/docs/tutorial/security#7-do-not-set-allowrunninginsecurecontent-to-true)
- [x] [Verify WebView Options Before Creation](https://www.electronjs.org/docs/tutorial/security#11-verify-webview-options-before-creation)
- [x] [Disable or limit navigation](https://www.electronjs.org/docs/tutorial/security#12-disable-or-limit-navigation)
- [x] [Disable or limit creation of new windows](https://www.electronjs.org/docs/tutorial/security#13-disable-or-limit-creation-of-new-windows)
- [x] [Do not use openExternal with untrusted content](https://www.electronjs.org/docs/tutorial/security#14-do-not-use-openexternal-with-untrusted-content): re-evaluate the existing solution
- [x] [Disable the remote module](https://www.electronjs.org/docs/tutorial/security#15-disable-the-remote-module) or [Filter the remote module](https://www.electronjs.org/docs/tutorial/security#16-filter-the-remote-module)
