### ISSUE TITLE
Roadmap: Enhanced password generation

### ISSUE THREAD

**Issue by Aetherinox** [keeweb/keeweb#2152]
### Summary
Password generation updates for the next major release of KeeWeb
- [x] Convert div to `textarea` with scrollbar for extra long passwords / phrases
- [x] Add passphrases
  - Selecting `ABC` by itself will output `WORD1 WORD2`
  - Selecting `abc` by itself will output `word1 word2`
  - Selecting `ABC` + `abc` will output `Word1 Word2`
- [x] Add SHA-512 (128-length) passwords
- [x] Add UUIDv4 preset
- [x] Add option to change bit hash to uppercase
- [x] Add ability to disable certain options like `spaces` when characters too low
- [x] Add `disabledElements` parameter so that certain checkboxes are disabled when a preset is loaded so that users know what options they have for each preset.
- [x] Add **Spaces** option which integrates spaces in passwords, but in a precise manner without spaces being scattered everywhere
- [x] Adjust password generation interface to auto-scale box and font size
