### ISSUE TITLE
🗺️ Roadmap: WebDAV

### ISSUE THREAD

**Issue by Aetherinox** [keeweb/keeweb#2219]
### Target Version

1.90.x

### Package

Keeweb

### Roadmap Details

- [ ] Attempt to dissect errors and put them into a human readable format
  - At present some errors will output as `object.object` with no information for the user. Makes it difficult to tell what an issue is, when really it should be throwing `401, 405`, etc.
- [ ] Add documentation for Windows IIS users for WebDAV
- [ ] Add documentation for using WebDAV with Traefik proxy
- [ ] Finish reviewing new feature https://github.com/keeweb/keeweb/pull/2218

**Comment by ZacZhangzhuo** [comment]
Hi, @Aetherinox , lovely to see the project is alive again bc of your contribution! 👍🏼  

I would also like to ping an issue #1956 to increase its visibility. it will be awesome if this issue fix could be a part of the roadmap
