### ISSUE TITLE
💡 Feature: UI question: how to hide All Items, Colors, Tags buttons v. 1.19.0

### ISSUE THREAD

**Issue by Aetherinox** [keeweb/keeweb#2221]
### Discussed in https://github.com/keeweb/keeweb/discussions/2220

<div type='discussions-op-text'>

<sup>Originally posted by **zoda61** December 24, 2024</sup>
Is there any appearance settings or other method to hide the All Items, Colors, Tags buttons at the top of the tree structure? The aim is to maximize the tree structure area when no need of these buttons. </div>

---

### Tasks
- [ ] Create way to make tags / colors in top-left toggable / hidden
- [ ] Categories should be top-most panel
- [ ] Fix padding between each entry title and icon

**Comment by Aetherinox** [comment]
Still need to finish the UI, but this is the just of how it will work
![iwGg5p8G71](https://github.com/user-attachments/assets/c54eba53-6caa-4cf4-9739-9976583c1ea0)

The setting is persistent, so it will last through multiple sessions until you click to restore.

The other tweak to do is that tags are re-sizable from the bottom part of the panel because tags were at the top, and bottom resize makes sense. So it'll have to be flipped.

But I'm also debating on whether to make this a setting or not (for the position), because I don't like to do dramatic changes to an interface and push the user into those new changes.  Not unless there's a discussion with the community first about a change they will not be able to control.

**Comment by zoda61** [comment]
In my opinion, users who use All Items, Tags or Colors no need changing the visibility all the time. Users usually has the desired settings regarding the UI they use daily. So as I can see on it no need to change the visibility from the upfront UI. It should be in the Appearance settings area and individual for each of the 3 buttons. I agree with you that changing the position of these buttons maybe to dramatic for existing users. I would leave they in position as in the original design and let users hide each of them separately in the Appearance settings if they wish. Maybe some users just use Colors but not Tags. So for them just hide the All Items and Tags buttons. Even the All Items can be unnecessary using the Show entries from all subgroups setting. However, the usage of the All Items, Colors and especially the Tags buttons should be redesigned as growing number of tags steal the whole tree area. In long term the data tree should positioned at the top and be always there.

"Even the All Items can be unnecessary using the Show entries from all subgroups setting." - explained:
As I know it can be only one root group (top folder in the tree) for Keepass databases, all others are subgroups. If the Show entries from all subgroups is activated in the settings, clicking on the root group has the same effect as the All Items button. Therefore the All Items button has not much extra function as I can see.

**Comment by Aetherinox** [comment]
So things have been split into a few ways.

Digging through these issues, two types of suggestions have come up, the toggle switch route, and then you wanting to just disable the elements all-together.

For me personally, I use multiple of the sections on the left, but going into the settings to enable-disable them would be a pain. I have a large list of entries on the left, and sometimes I want the full list to show, or as much as possible.

So I've combined these into a few different settings.

![dR9HWYIxWw](https://github.com/user-attachments/assets/d54061ca-3340-4498-b55a-8fd75bfa2426)

If all three aspects on the left are disabled completely, then this removes the 4th option, which is the toggle switch. And then if any of the options are not disabled, a 4th setting will appear, which allows for those panels to be toggled.

![JrxnKLMNgy](https://github.com/user-attachments/assets/97c37f72-7a89-4904-bea9-0fafdfb54f9e)

And then the toggle can also be disabled / enabled

![97y6SZ5Iwn](https://github.com/user-attachments/assets/15ef6d50-0bca-4620-87b0-305620f56f5b)

**Comment by zoda61** [comment]
I understand your logic, it's very flexible in that way, it´s great. My only concern, if it is decided to change position for the Colors and Tags, the toggling position of the All Items button on the top. Steal a lot of space. May be it would be enough just an icon for this function in the middle column if there is space for that before the + icon or before the search field.

The position of the Colors and Tags list is better down with a scrollable list when many tags are defined. What happening when you have a large group tree and many Tags defined and the Tags are on? Will be 2 scrollable area? One for the group tree and an other for the Tags?

**Comment by zoda61** [comment]
As the orginal UI design, the All Items, Colors and Tags all are fast filter options and probably therefore they are grouped together.

**Comment by Aetherinox** [comment]
> May be it would be enough just an icon for this function in the middle column if there is space for that before the + icon or before the search field.

The middle column may have its own problems, as some people have one or two vaults open, but others have a multitude, hence why I opted out of the main workflow.

> What happening when you have a large group tree and many Tags defined and the Tags are on?

The functionality remains the same. Both aspects maintain their down scrollbar, tags, and the groups separately. If you create too many groups that exceed the panel's dimensions, a vertical scrollbar will pop up for the groups, which will be you either need to resize that frame to remove the scrollbar, or leave it as-is.  Because if I made groups and tags a single scrollbar, that would result in a pain if having to manage one or the other, and fighting the one you're not interested in.

As far as how the panels work, same functionality, just different order. I don't want to divert too far away from that. Not unless the framework requires that we revise the code for some unforeseen reason.

For now this just takes care of the basics for cleaning up that section. More will be looked at later. Nothing is set in stone going forward, as the big priority is getting the framework finished. These are just quick edits to implement options for different tastes.

For now, the more important thing is finishing up the WebDAV addition, because that's one of the last things holding us back. Then I'll look at additional UI adjustments when there's some free time.

**Comment by zoda61** [comment]
OK, I understand. Just one more thing to count with later. As I can see in the original design, the search function searchs in just the already listed items. May be therefore the original design keep all together in the upper area to eliminate a lot of mouse movement between the filter and search function. First you have to filter a list and then can you search within it, if I understod it right.
